language: node_js
node_js:
  - "6"
  - "7"
  - "8"
install:
  - npm install
script:
  - npm run eslint
  - npm run stylelint
  - npm run test
env:
  - REACT=16.2
bundler_args: --retry 2
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
after_script:
    - npm run coveralls
